spring:
  application:
    name: gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    #    url: jdbc:mysql://192.168.1.24:3306/df_demo
    #    url: jdbc:mysql://localhost:3306/df_demo_05
    url: jdbc:mysql://192.168.110.95:3306/boen_qms_vn_cg?serverTimezone=Asia/Shanghai
    username: root2
    password: root
  servlet:
    multipart:
#      location: /Users/dafenqi/Downloads #上传文件临时目录
      max-file-size: 10MB
      max-request-size: 500MB
file:
  upload-dir: /home/static # 文件上传目录配置，需要修改
server:
  port: 60001
swagger:
  enabled: true
gateway:
    ipconfig: http://10.77.30.11:8089 #需要修改
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath*:xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true